#!/bin/bash

RUN_DIR=/var/vcap/sys/run/InterviewTimer
LOG_DIR=/var/vcap/sys/log/InterviewTimer
PIDFILE=${RUN_DIR}/pid

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

#    cd /var/vcap/packages/ardo_app

#    export PATH=/var/vcap/packages/ruby_1.9.3/bin:$PATH

#    exec /var/vcap/packages/ruby_1.9.3/bin/bundle exec \
#      rackup -p <%= properties.web_ui.port %> \
      >>  $LOG_DIR/InterviewTimer.stdout.log \
      2>> $LOG_DIR/InterviewTimer.stderr.log

    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac
